name: Flora Eco Hotel
favicon: null
layout_spectrum: 0.6877122009173036
typography_spectrum: 0.29209107835777104
title: Flora Eco Hotel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.45903502963483334
  lightness: 0.39398712175898254
  saturation: 0.6205454873852432
  rhythmicContrast: 0.5245257299393415
purpose: []
